all: v2

v2: Ass4_Ver2.py
	python3 Ass4_Ver2.py ../Dataset

v3: Ass4_Ver3.py
	python3 Ass4_Ver3.py ../Dataset	

data_process: Data_processing.py
	python3 Data_processing.py ../Dataset

HPC_Auto: HPC_Auto.py
	python3 HPC_Auto.py ../Dataset
